package dataBaseUtils;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ResultDAO {

    public ResultDAO() {
        createTableIfNotExists();
    }

    private void createTableIfNotExists() {
        String sql =
                "CREATE TABLE IF NOT EXISTS RESULTS (" +
                "  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  X DOUBLE," +
                "  Y DOUBLE," +
                "  R DOUBLE," +
                "  RESULT BOOLEAN," +
                "  TIME TIMESTAMP" +
                ")";

        try (Connection conn = DatabaseUtil.getConnection();
             Statement st = conn.createStatement()) {
            st.executeUpdate(sql);
        } catch (SQLException e) {
            throw new RuntimeException("Ошибка создания таблицы RESULTS", e);
        }
    }

    public void save(ResultEntity result) {
        String sql = "INSERT INTO RESULTS (X, Y, R, RESULT, TIME) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseUtil.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setDouble(1, result.getX());
            ps.setDouble(2, result.getY());
            ps.setDouble(3, result.getR());
            ps.setBoolean(4, result.isResult());
            LocalDateTime time = result.getTime() != null ? result.getTime() : LocalDateTime.now();
            ps.setTimestamp(5, Timestamp.valueOf(time));

            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Ошибка сохранения результата", e);
        }
    }

    public List<ResultEntity> getAll() {
        String sql = "SELECT ID, X, Y, R, RESULT, TIME FROM RESULTS ORDER BY ID DESC";
        List<ResultEntity> list = new ArrayList<>();

        try (Connection conn = DatabaseUtil.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                ResultEntity entity = new ResultEntity();
                entity.setId(rs.getLong("ID"));
                entity.setX(rs.getDouble("X"));
                entity.setY(rs.getDouble("Y"));
                entity.setR(rs.getDouble("R"));
                entity.setResult(rs.getBoolean("RESULT"));
                Timestamp ts = rs.getTimestamp("TIME");
                entity.setTime(ts != null ? ts.toLocalDateTime() : null);
                list.add(entity);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Ошибка получения списка результатов", e);
        }

        return list;
    }

    public void clear() {
        try (Connection conn = DatabaseUtil.getConnection();
             Statement st = conn.createStatement()) {
            st.executeUpdate("TRUNCATE TABLE RESULTS");
        } catch (SQLException e) {
            throw new RuntimeException("Ошибка очистки таблицы RESULTS", e);
        }
    }
}
